---
title: "Course Lecture Viewing Summary"
output: html_notebook
---

```{r}
source('global.R')

data.dir <- '~/projects/shinyboard/data'
course.term <- '2017-02'
course.series.id <- '20170224816'
actions.index <- 'useractions-matterhorn-production-2017.*'
inpoint.interval <- 300
```

```{r}
if (rollcall.path == "") {
  rollcall.path <- sprintf("%s/rollcall.%s.csv", data.dir, course.term)
}
rollcall <- tbl_df(
  read.csv(
    rollcall.path, stringsAsFactors = F
    )
  ) %>% filter(series == course.series.id & reg_level != 'S')
episodes <- getEpisodes('2017-02', course.series.id) %>% 
  select(mpid, title, duration, available, start, live_duration) %>%
  mutate(available = coalesce(available, start))
```

```{r}

calcAttendance <- function(mpid, duration, live = F) {
  student.stats <- viewingStats(
    actions.index, 
    '2017-02', 
    mpid = mpid, 
    live = live,
    aggs = termAgg(
      "huid", 
      sub_aggs = histogramAgg(
        "action.inpoint", 
        toString(inpoint.interval), 
        agg.name = "inpoints"
      )
    )
#   ,print.json = T
  )
  if (nrow(student.stats) != 0) {
    duration.in.seconds <- duration / 100
    student.stats <- student.stats %>% 
      rowwise() %>% 
      mutate(
        huid=by_huid.buckets.key,
        intervals=nrow(by_huid.buckets.inpoints.buckets),
        watched=round((intervals / (duration.in.seconds / inpoint.interval)) * 100)
      ) %>%
      select(huid, intervals, watched) %>%
      left_join(rollcall)
  }
  list(student.stats)
}

```

```{r warning=FALSE, message=FALSE}
episode.stats <- episodes %>% 
  rowwise() %>% 
  mutate(
    stats.vod              = calcAttendance(mpid, duration, live = F),
    stats.live             = calcAttendance(mpid, live_duration, live = T),
    huids.vod              = list(stats.vod$huid),
    huids.live             = list(stats.live$huid),
    huids.vod.dce          = list(filter(stats.vod, huid %in% rollcall$huid)$huid),
    huids.live.dce         = list(filter(stats.live, huid %in% rollcall$huid)$huid),
    viewers.total          = length(union(huids.vod, huids.live)),
    viewers.vod            = length(huids.vod),
    viewers.live           = length(huids.live),
    viewers.both           = length(intersect(huids.vod, huids.live)),
    viewers.total.dce      = length(union(huids.vod.dce, huids.live.dce)),
    viewers.vod.dce        = length(huids.vod.dce),
    viewers.live.dce       = length(huids.live.dce),
    viewers.both.dce       = length(intersect(huids.vod.dce, huids.live.dce)),
    attendance.vod.pct     = round((viewers.vod.dce / nrow(rollcall)) * 100),
    attendance.live.pct    = round((viewers.live.dce / nrow(rollcall)) * 100),
    attendance.total.pct   = round((viewers.total.dce / nrow(rollcall)) * 100)
  )
```

```{r}
results <- episode.stats %>%
  arrange(available) %>%
  select(-starts_with('stats'), -starts_with('huids'), -mpid, -ends_with('duration'), -start) 
write_csv(results, sprintf("./attendance_summary_%s.csv", course.series.id))
```


